### ISSUE TITLE
Why not using Jekyll instead of Hexo?

### ISSUE THREAD

**Issue by kaoussi** [MoroccoJS/MoroccoJS#3]
I think Jekyll is a great static site generator too with awesome features!

**Comment by YoussefKababe** [comment]
Hey buddy! 

Thank you so much for your interest in contributing to the community.

We chose Hexo because we wanted to use a JavaScript based solution to build our website. 

We started working on a new version of the website which we'll be releasing soon. The new website will be easier to maintain, better organized, and will provide a simpler way to organize content. However, while we welcome everyone to suggest new content for the community, we will put some simple criteria on the quality before the core members can accept to publish it. More information will be available soon! 

We're also working on expanding the community by organizing some events in the very near future. 

Until then, please feel free to join the discussion on Slack: https://slack.moroccojs.org/, and you can also start writing some interesting tutorials or articles about any JavaScript related subject, we'll be glad to add them to the new Website!

**Comment by kaoussi** [comment]
Sure I will! thanks :)
